### ISSUE TITLE
「謹製」の使い方

### ISSUE THREAD

**Issue by matelier** [Materials-Science-Software-Consortium/phase0_install#6]
> Windows謹製の仕組みであり，

（Windowsが作るわけではないので、Microsoft社謹製を意図した表現だろうと推察しますが）
「謹製」は謙譲の意味を含むので、他人（他社）が作成したものに使うのは適切ではない、と思います。

**Comment by jkoga-asms** [comment]
表現をかえました
1fa9e2b5c09e07cbd26cc99d37acd8f56f77e9be
